export const GLOSSARY: { term: string; def: string }[] = [
  { term: "Unclaimed money", def: "Money in a bank, insurer, provident fund or company that the owner or family has not collected, often because nobody knew it existed." },
  { term: "Nominee", def: "A person named on an account or policy to receive the money. Under Indian law the nominee usually holds it in trust for the legal heirs." },
  { term: "Legal heir", def: "A family member entitled to the money by law when there is no valid nominee. Who counts depends on the personal law that applies." },
  { term: "Legal heir certificate", def: "A certificate from the local revenue office (tehsildar) that lists the family members entitled. Usually 15 to 30 days." },
  { term: "Succession certificate", def: "A court order that names who may collect debts and securities. Needed for larger amounts when there is no nominee. Court fees are a percentage of the value, capped by state." },
  { term: "Indemnity bond", def: "A signed promise on stamp paper to return the money if someone with a better claim appears. Banks accept it instead of a court order for smaller amounts." },
  { term: "AIS (Annual Information Statement)", def: "A yearly statement from the Income Tax Department listing interest, dividends and other income paid to a person. It reveals every bank and company that paid them." },
  { term: "UDGAM", def: "RBI's portal to search unclaimed bank deposits across 30 banks in one place. Deposits with no activity for 10 years or more." },
  { term: "DEA Fund", def: "The Depositor Education and Awareness Fund, where banks move deposits unclaimed for 10 years. The money can still be claimed from the bank." },
  { term: "IEPF", def: "The Investor Education and Protection Fund. Companies move dividends unpaid for 7 years, and the related shares, here. Families can claim them back online." },
  { term: "MITRA", def: "SEBI's Mutual fund Investment Tracing and Retrieval Assistant, a portal to find forgotten mutual fund folios." },
  { term: "Bima Bharosa", def: "IRDAI's insurance grievance portal, which also links every insurer's unclaimed amounts search." },
  { term: "EPFO and UAN", def: "The Employees' Provident Fund Organisation manages provident fund for salaried workers. The UAN is the 12-digit member number." },
  { term: "Ombudsman", def: "A free official who resolves complaints against a bank (RBI), insurer (IRDAI) or other institution when they do not respond." },
  { term: "Rule engine", def: "A written checklist the computer follows exactly. The same input always gives the same result, and every rule has tests." },
  { term: "Structured output", def: "A way of making the AI answer in a fixed format (a JSON schema), so the app never breaks on an unexpected answer." },
  { term: "The Two AI Debate", def: "Two AI reviewers argue for and against a result, and a third gives a verdict with reasons and risks. It catches gaps a single answer can miss." },
  { term: "Bring Your Own (BYO)", def: "Institutions can use Virasat with their own data, their own AI key, or their own claim rules." },
  { term: "Lakh and crore", def: "1 lakh = 1,00,000 (one hundred thousand). 1 crore = 1,00,00,000 (ten million). 1 lakh crore = one trillion." },
  { term: "DPDP Act 2023", def: "India's Digital Personal Data Protection Act: consent, purpose limitation, minimal data, and the right to delete." },
];
