"""Regenerate docs/DEMO-SCRIPT.md from beats.py, so the two cannot disagree.

    python video/script_doc.py

A prose script and a built film cannot be compared by reading them. This one
is written from the same file the narrator reads, so the words in the document
are the words in the film, always.
"""
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from beats import BEATS, CEILING, ENGINE, RATE, SITE, VOICE, estimate  # noqa: E402

DOC = pathlib.Path(__file__).parent.parent / "docs" / "DEMO-SCRIPT.md"

# What the camera does for each beat, mirroring the actions in record.py.
SHOTS = {
    "hello": "Landing page hero, already loaded. Cursor still.",
    "problem": "Click Try it now. Reveal the three cards Virasat read, and point at the passbook, the bond and the certificate, one per sentence.",
    "name-it": "Ease back to the top. Rest on the Virasat logo.",
    "find": "Return to the cards. Point at a confidence badge, then ease down to the total.",
    "ais": "Scroll to Tax statement (AIS). Press Use Ramesh's sample AIS, then reveal the rows that were not in the papers.",
    "search": "Scroll to Unpaid dividends by name. Search the full name, hold the no-match, then search the shorter name and show three years of dividends.",
    "route": "Next: claim this money. Pick State Bank of India, answer nominee Yes and relation Spouse, then Get my route and forms. Point at the rule id, then the checklist.",
    "review": "Open the full review. Point at the Challenger on the name mismatch, then the Referee verdict.",
    "pack": "Download the claim pack, then open Track and show the new claim.",
    "include": "Switch the language to Hindi and let the route and checklist re-render.",
    "close": "Back to English, open /proof and hold on the cost table. Point at the headline, the total, then the return per rupee. Do not scroll.",
    "thanks": "Hold on the product in its finished state.",
}


def main():
    total = sum(b["pause"] + estimate(b["say"]) for b in BEATS)
    out = [
        "# Demo film: the script, as built",
        "",
        "Generated by `python video/script_doc.py` from `video/beats.py`, which is",
        "what the narrator actually reads. Edit the beats file, not this one: a prose",
        "script and a built film cannot be compared by reading them, and the last time",
        "they were kept apart the document still said things the film did not.",
        "",
        "%d beats, %d words, about %d seconds of speech at %s, %s, rate %s."
        % (len(BEATS), sum(len(b["say"].split()) for b in BEATS), total, VOICE, ENGINE, RATE),
        "Hard ceiling %d seconds. Recorded against %s." % (CEILING, SITE),
        "",
        "---",
        "",
    ]
    for i, b in enumerate(BEATS, 1):
        out += ["## %d. %s" % (i, b["id"]),
                "",
                "**Camera:** %s" % SHOTS.get(b["id"], ""),
                "",
                "**Say:** %s" % b["say"],
                ""]
    DOC.write_text("\n".join(out), encoding="utf-8")
    print("wrote %s from beats.py" % DOC.name)


if __name__ == "__main__":
    main()
