/**
 * Writes CREDITS.md from src/lib/credits.ts, so the file in the repository and
 * the page on the site can never disagree about who we owe.
 *
 *   npm run credits
 *
 * A test fails the build if the file on disk has fallen behind the source.
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { HOW_IT_WAS_BUILT, RUNTIME, SERVICES, TOOLING, type Credit } from "../src/lib/credits";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const block = (heading: string, note: string, items: Credit[]) =>
  [`## ${heading}`, "", note, "", ...items.map((c) => `- [${c.name}](${c.url}), ${c.licence}. ${c.what}`), ""].join("\n");

export const CREDITS_MD = [
  "# Credits",
  "",
  "Virasat is MIT licensed, and stands on other people's work. Everything below is",
  "used under its own licence. This file is generated by `npm run credits` from",
  "`src/lib/credits.ts`, which is also what the Sources page on the site renders.",
  "",
  block("In the product", "Runs in the family's browser, or on the server answering them.", RUNTIME),
  block("For building and checking", "Never reaches a visitor. These are how we know the numbers are true.", TOOLING),
  block("Services", "Where it runs.", SERVICES),
  "## How this was built",
  "",
  HOW_IT_WAS_BUILT.tools,
  "",
  "The hackathon rules allow AI development tools and hold us responsible for what",
  "we submit. Here is how we take that on:",
  "",
  ...HOW_IT_WAS_BUILT.responsibility.map((r) => `- ${r}`),
  "",
  "Data sources for every number on the site are listed at [/references](https://virasat-indol.vercel.app/references).",
  "",
].join("\n");

writeFileSync(join(root, "CREDITS.md"), CREDITS_MD);
console.log("wrote CREDITS.md");
